kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: hpa-nodejs
  namespace: hpa-nodejs
spec:
  scaleTargetRef:
    kind: Deployment
    name: hpa-nodejs
    apiVersion: apps/v1
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65