apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: prom-scaled-hpa-nodejs
  namespace: hpa-nodejs
spec:
  scaleTargetRef:
    name: hpa-nodejs
    kind: Deployment
  cooldownPeriod: 120
  maxReplicaCount: 10
  minReplicaCount: 1
  pollingInterval: 10 
  advanced:
    restoreToOriginalReplicaCount: false 
    horizontalPodAutoscalerConfig:
      behavior: 
        scaleDown:
          stabilizationWindowSeconds: 120
          policies:
          - type: Percent
            value: 20
            periodSeconds: 60
  triggers:
  - type: prometheus 
    metadata:
      serverAddress: https://thanos-querier.openshift-monitoring.svc.cluster.local:9092
      namespace: hpa-nodejs 
      metricName: nodejs_eventloop_lag_mean_seconds
      name: nodejs_eventloop_lag_mean_seconds
      # If mean event loop lag is above 40 milliseconds, scale up!
      threshold: '40'
      query: avg(nodejs_eventloop_lag_mean_seconds)*1000
      authModes: "bearer"
    authenticationRef: 
      name: keda-trigger-auth-prometheus